<?php
return <<<PHP
<?php

declare(strict_types=1);

namespace {namespace};

use Symfony\Component\Yaml\Yaml;
use Core\Config\Attributes\Config;
{uses}
/**
 * @generated by yaml file {yamlFileName}.yaml
 */
#[Stateful]
#[Config(name: "{yamlFileName}", interface: {interfaceName}::class)]
class {className} implements {interfaceName}
{
    {properties}

    public function __construct()
    {
        \$yamlFilePath = __DIR__ . '/../../yaml/{yamlFileName}.yaml';

        if (!file_exists(\$yamlFilePath)) {
            throw new \\InvalidArgumentException("Файл не найден: " . \$yamlFilePath);
        }

        \$data = Yaml::parseFile(\$yamlFilePath);

        {constructorAssignments}    
    }

    {getters}
}
PHP;
